Added penlight download URL
Will overcome:
```
Using https://luarocks.org/penlight-1.5.4-1.rockspec... switching to 'build' mode

Error: Failed installing dependency: https://luarocks.org/busted-2.0.rc13-0.rockspec - Failed installing dependency: https://luarocks.org/penlight-1.5.4-1.rockspec - Error fetching file: Failed downloading http://stevedonovan.github.io/files/penlight-1.5.4.zip - penlight-1.5.4.zip
make: *** [dependencies] Error 1
make[1]: *** [test-run] Error 2
make[1]: [tmp-export] Error 1 (ignored)
make[1]: Leaving directory `/home/circleci/project'
```